package spring.boot.dynamicdatasource.dao.model;

import java.io.Serializable;
import java.util.Date;

public class AppointmentClassInfo implements Serializable {

    private static final long serialVersionUID = 265654325424L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Long id;
    private Long scheduleId;
    private Long appointId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.class_type_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer classTypeId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.class_type_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String classTypeName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.class_info_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String classInfoName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.status
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer status;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.store_area_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Long storeAreaId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.store_area_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String storeAreaName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.coach_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Long coachId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.coach_stage_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String coachStageName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.coach_mobile
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String coachMobile;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.coach_login_mobile
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String coachLoginMobile;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.user_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Long userId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.user_nike
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String userNick;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.user_mobile
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String userMobile;

    private String goodsNo;
    private String goodsName;
    private String  orderNo;

    private Integer appointChannel;

    public Long getAppointId() {
        return appointId;
    }

    public void setAppointId(Long appointId) {
        this.appointId = appointId;
    }

    public String getOrderNo() {
        return orderNo;
    }

    public void setOrderNo(String orderNo) {
        this.orderNo = orderNo;
    }

    public String getGoodsName() {
        return goodsName;
    }

    public void setGoodsName(String goodsName) {
        this.goodsName = goodsName;
    }

    public String getGoodsNo() {
        return goodsNo;
    }

    public void setGoodsNo(String goodsNo) {
        this.goodsNo = goodsNo;
    }

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.appointment_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer appointmentTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.appointment_begin_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer appointmentBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.appointment_end_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer appointmentEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.user_sign_begin_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer userSignBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.user_sign_end_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer userSignEndTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.coach_sign_begin_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer coachSignBeginTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.coach_sign_end_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer coachSignEndTime;


    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.ctime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.mtime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column appointment_class_info.isDel
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer isdel;

    private Long lessonId;
    private Long userAvailId;

    private Integer signChannel;

    public Long getScheduleId() {
        return scheduleId;
    }

    public void setScheduleId(Long scheduleId) {
        this.scheduleId = scheduleId;
    }

    public Integer getAppointChannel() {
        return appointChannel;
    }

    public void setAppointChannel(Integer appointChannel) {
        this.appointChannel = appointChannel;
    }

    public Integer getSignChannel() {
        return signChannel;
    }

    public void setSignChannel(Integer signChannel) {
        this.signChannel = signChannel;
    }

    public Long getLessonId() {
        return lessonId;
    }

    public void setLessonId(Long lessonId) {
        this.lessonId = lessonId;
    }

    public Long getUserAvailId() {
        return userAvailId;
    }

    public void setUserAvailId(Long userAvailId) {
        this.userAvailId = userAvailId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.id
     *
     * @return the value of appointment_class_info.id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.id
     *
     * @param id the value for appointment_class_info.id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.class_type_id
     *
     * @return the value of appointment_class_info.class_type_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getClassTypeId() {
        return classTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.class_type_id
     *
     * @param classTypeId the value for appointment_class_info.class_type_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setClassTypeId(Integer classTypeId) {
        this.classTypeId = classTypeId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.class_type_name
     *
     * @return the value of appointment_class_info.class_type_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public String getClassTypeName() {
        return classTypeName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.class_type_name
     *
     * @param classTypeName the value for appointment_class_info.class_type_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setClassTypeName(String classTypeName) {
        this.classTypeName = classTypeName == null ? null : classTypeName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.class_info_name
     *
     * @return the value of appointment_class_info.class_info_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public String getClassInfoName() {
        return classInfoName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.class_info_name
     *
     * @param classInfoName the value for appointment_class_info.class_info_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setClassInfoName(String classInfoName) {
        this.classInfoName = classInfoName == null ? null : classInfoName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.status
     *
     * @return the value of appointment_class_info.status
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getStatus() {
        return status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.status
     *
     * @param status the value for appointment_class_info.status
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setStatus(Integer status) {
        this.status = status;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.store_area_id
     *
     * @return the value of appointment_class_info.store_area_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Long getStoreAreaId() {
        return storeAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.store_area_id
     *
     * @param storeAreaId the value for appointment_class_info.store_area_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setStoreAreaId(Long storeAreaId) {
        this.storeAreaId = storeAreaId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.store_area_name
     *
     * @return the value of appointment_class_info.store_area_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public String getStoreAreaName() {
        return storeAreaName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.store_area_name
     *
     * @param storeAreaName the value for appointment_class_info.store_area_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setStoreAreaName(String storeAreaName) {
        this.storeAreaName = storeAreaName == null ? null : storeAreaName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.coach_id
     *
     * @return the value of appointment_class_info.coach_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Long getCoachId() {
        return coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.coach_id
     *
     * @param coachId the value for appointment_class_info.coach_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setCoachId(Long coachId) {
        this.coachId = coachId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.coach_stage_name
     *
     * @return the value of appointment_class_info.coach_stage_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public String getCoachStageName() {
        return coachStageName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.coach_stage_name
     *
     * @param coachStageName the value for appointment_class_info.coach_stage_name
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setCoachStageName(String coachStageName) {
        this.coachStageName = coachStageName == null ? null : coachStageName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.coach_mobile
     *
     * @return the value of appointment_class_info.coach_mobile
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public String getCoachMobile() {
        return coachMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.coach_mobile
     *
     * @param coachMobile the value for appointment_class_info.coach_mobile
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setCoachMobile(String coachMobile) {
        this.coachMobile = coachMobile == null ? null : coachMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.coach_login_mobile
     *
     * @return the value of appointment_class_info.coach_login_mobile
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public String getCoachLoginMobile() {
        return coachLoginMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.coach_login_mobile
     *
     * @param coachLoginMobile the value for appointment_class_info.coach_login_mobile
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setCoachLoginMobile(String coachLoginMobile) {
        this.coachLoginMobile = coachLoginMobile == null ? null : coachLoginMobile.trim();
    }



    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.user_id
     *
     * @return the value of appointment_class_info.user_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Long getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.user_id
     *
     * @param userId the value for appointment_class_info.user_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setUserId(Long userId) {
        this.userId = userId;
    }

    public String getUserNick() {
        return userNick;
    }

    public void setUserNick(String userNick) {
        this.userNick = userNick;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.user_mobile
     *
     * @return the value of appointment_class_info.user_mobile
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public String getUserMobile() {
        return userMobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.user_mobile
     *
     * @param userMobile the value for appointment_class_info.user_mobile
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setUserMobile(String userMobile) {
        this.userMobile = userMobile == null ? null : userMobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.appointment_time
     *
     * @return the value of appointment_class_info.appointment_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getAppointmentTime() {
        return appointmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.appointment_time
     *
     * @param appointmentTime the value for appointment_class_info.appointment_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setAppointmentTime(Integer appointmentTime) {
        this.appointmentTime = appointmentTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.appointment_begin_time
     *
     * @return the value of appointment_class_info.appointment_begin_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getAppointmentBeginTime() {
        return appointmentBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.appointment_begin_time
     *
     * @param appointmentBeginTime the value for appointment_class_info.appointment_begin_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setAppointmentBeginTime(Integer appointmentBeginTime) {
        this.appointmentBeginTime = appointmentBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.appointment_end_time
     *
     * @return the value of appointment_class_info.appointment_end_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getAppointmentEndTime() {
        return appointmentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.appointment_end_time
     *
     * @param appointmentEndTime the value for appointment_class_info.appointment_end_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setAppointmentEndTime(Integer appointmentEndTime) {
        this.appointmentEndTime = appointmentEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.user_sign_begin_time
     *
     * @return the value of appointment_class_info.user_sign_begin_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getUserSignBeginTime() {
        return userSignBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.user_sign_begin_time
     *
     * @param userSignBeginTime the value for appointment_class_info.user_sign_begin_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setUserSignBeginTime(Integer userSignBeginTime) {
        this.userSignBeginTime = userSignBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.user_sign_end_time
     *
     * @return the value of appointment_class_info.user_sign_end_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getUserSignEndTime() {
        return userSignEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.user_sign_end_time
     *
     * @param userSignEndTime the value for appointment_class_info.user_sign_end_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setUserSignEndTime(Integer userSignEndTime) {
        this.userSignEndTime = userSignEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.coach_sign_begin_time
     *
     * @return the value of appointment_class_info.coach_sign_begin_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getCoachSignBeginTime() {
        return coachSignBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.coach_sign_begin_time
     *
     * @param coachSignBeginTime the value for appointment_class_info.coach_sign_begin_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setCoachSignBeginTime(Integer coachSignBeginTime) {
        this.coachSignBeginTime = coachSignBeginTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.coach_sign_end_time
     *
     * @return the value of appointment_class_info.coach_sign_end_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getCoachSignEndTime() {
        return coachSignEndTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.coach_sign_end_time
     *
     * @param coachSignEndTime the value for appointment_class_info.coach_sign_end_time
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setCoachSignEndTime(Integer coachSignEndTime) {
        this.coachSignEndTime = coachSignEndTime;
    }


    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.ctime
     *
     * @return the value of appointment_class_info.ctime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.ctime
     *
     * @param ctime the value for appointment_class_info.ctime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.mtime
     *
     * @return the value of appointment_class_info.mtime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.mtime
     *
     * @param mtime the value for appointment_class_info.mtime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column appointment_class_info.isDel
     *
     * @return the value of appointment_class_info.isDel
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column appointment_class_info.isDel
     *
     * @param isdel the value for appointment_class_info.isDel
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }
}