package spring.boot.dynamicdatasource.dao.model;

import java.io.Serializable;
import java.util.Date;

/**
 * Created by 顷强强 on 2018/3/5.
 */
public class LessonPlan implements Serializable {

    private static final long serialVersionUID = 265654325424L;
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_plan.id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Long id;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_plan.class_info_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Long classInfoId;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_plan.remark
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String remark;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_plan.ctime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer ctime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_plan.mtime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Date mtime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_plan.isDel
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private Integer isdel;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_plan.warm_up
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String warmUp;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_plan.subject_info
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String subjectInfo;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column lesson_plan.cold_down
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    private String coldDown;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_plan.id
     *
     * @return the value of lesson_plan.id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Long getId() {
        return id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_plan.id
     *
     * @param id the value for lesson_plan.id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setId(Long id) {
        this.id = id;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_plan.class_info_id
     *
     * @return the value of lesson_plan.class_info_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Long getClassInfoId() {
        return classInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_plan.class_info_id
     *
     * @param classInfoId the value for lesson_plan.class_info_id
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setClassInfoId(Long classInfoId) {
        this.classInfoId = classInfoId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_plan.remark
     *
     * @return the value of lesson_plan.remark
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public String getRemark() {
        return remark;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_plan.remark
     *
     * @param remark the value for lesson_plan.remark
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setRemark(String remark) {
        this.remark = remark == null ? null : remark.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_plan.ctime
     *
     * @return the value of lesson_plan.ctime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getCtime() {
        return ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_plan.ctime
     *
     * @param ctime the value for lesson_plan.ctime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setCtime(Integer ctime) {
        this.ctime = ctime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_plan.mtime
     *
     * @return the value of lesson_plan.mtime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Date getMtime() {
        return mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_plan.mtime
     *
     * @param mtime the value for lesson_plan.mtime
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setMtime(Date mtime) {
        this.mtime = mtime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_plan.isDel
     *
     * @return the value of lesson_plan.isDel
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public Integer getIsdel() {
        return isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_plan.isDel
     *
     * @param isdel the value for lesson_plan.isDel
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setIsdel(Integer isdel) {
        this.isdel = isdel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_plan.warm_up
     *
     * @return the value of lesson_plan.warm_up
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public String getWarmUp() {
        return warmUp;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_plan.warm_up
     *
     * @param warmUp the value for lesson_plan.warm_up
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setWarmUp(String warmUp) {
        this.warmUp = warmUp == null ? null : warmUp.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_plan.subject_info
     *
     * @return the value of lesson_plan.subject_info
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public String getSubjectInfo() {
        return subjectInfo;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_plan.subject_info
     *
     * @param subjectInfo the value for lesson_plan.subject_info
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setSubjectInfo(String subjectInfo) {
        this.subjectInfo = subjectInfo == null ? null : subjectInfo.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column lesson_plan.cold_down
     *
     * @return the value of lesson_plan.cold_down
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public String getColdDown() {
        return coldDown;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column lesson_plan.cold_down
     *
     * @param coldDown the value for lesson_plan.cold_down
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    public void setColdDown(String coldDown) {
        this.coldDown = coldDown == null ? null : coldDown.trim();
    }
}
