package spring.boot.dynamicdatasource.dao.mapper;


import org.apache.ibatis.annotations.Param;
import org.springframework.stereotype.Repository;
import spring.boot.dynamicdatasource.dao.model.AppointmentClassInfo;
import spring.boot.dynamicdatasource.dao.model.AppointmentStoreAreaBean;
import spring.boot.dynamicdatasource.dao.model.LessonPlan;
import spring.boot.dynamicdatasource.dao.model.QueryClassInfoDao;

import java.util.List;
@Repository
public interface AppointmentClassInfoMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_class_info
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_class_info
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    int insert(AppointmentClassInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_class_info
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    AppointmentClassInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_class_info
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    List<AppointmentClassInfo> selectAll();



    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table appointment_class_info
     *
     * @mbggenerated Wed Mar 15 17:37:28 CST 2017
     */
    int updateByPrimaryKey(AppointmentClassInfo record);





}